### ISSUE TITLE
ERROR: Timed out waiting for target element: ('class name', 'ufss-slotselect-container')

### ISSUE THREAD

**Issue by BrendanBTO** [mark-thompson/whole-foods-deliverance#28]
Getting this error just after "Checking for available slots

**Comment by mark-thompson** [comment]
@BrendanBTO does your slot select page look like this? 
<img width="529" alt="79279106-4744f480-7e7b-11ea-84a1-78c3f38b8ff9" src="https://user-images.githubusercontent.com/7841836/79702031-c1a4b880-826f-11ea-943b-2eafeeccaca0.png">
If it does, there is an open issue (#19) for that version.
Otherwise, please run the program with `--debug` and upload the `source_dump_*` file produced when the error is encountered again. (be sure to redact any personal information on the page)

**Comment by BrendanBTO** [comment]
Yeah that's it. In my area they recently switched to the 3 days view. OK I'll check for updates on #19 then. Thank you for the efforts, much appreciated.
