### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81

### ISSUE THREAD

**Issue by b3nw** [mark-thompson/whole-foods-deliverance#7]
on windows, I had some trouble with this, the solution was:

`pip install --upgrade chromedriver-binary`

Then add to imports:
`from webdriver_manager.chrome import ChromeDriverManager`

And update: 
```
log.info('Invoking Selenium Chrome webdriver')
driver = webdriver.Chrome()
```

to:
```
    log.info('Invoking Selenium Chrome webdriver')
    driver = webdriver.Chrome(ChromeDriverManager().install())
```

**Comment by mark-thompson** [comment]
It appears v81 is the new Chrome stable version (as of yesterday). I've updated the requirements to reflect this.
Let me know if this is still a problem and I'll re-open

**Comment by b3nw** [comment]
this still throws errors for me, but the above workaround works, so I'll leave this closed since it seems I'm the only one running into it.

**Comment by mark-thompson** [comment]
@b3nw try nuking the env with `rm -rf env` or whatever the Powershell equivalent is, then create it and re-install requirements

**Comment by FranklinYu** [comment]
I also ran into this. It didn’t help to simply upgrade ChromeDriver to latest version on PyPI, because that one is 88, while the latest stable Chrome is actually 87. I fixed it by manually editing the `requirements.txt`. I feel like it would be necessary to keep the version in `requirements.txt` synced with the one currently installed, but I guess this is very difficult to automate. Do you think it helps to mention it in ReadMe? Something like

> Please check your Chrome version, and update the version of `chromedriver-binary` in `requirements.txt` accordingly. The list of available versions is available [on PyPI](https://pypi.org/project/chromedriver-binary/#history).

By the way, I didn’t need the line for `ChromeDriverManager().install()`.
